name: Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  website:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Build Website
        run: |
          npm i
          npm run build
        env:
          GITHUB_REPO: ${{github.repository}}
          Z3_BUILD_TAG: "v1.0.1"

      - name: Deploy Website
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: dist
